import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMetaSEO } from "@/hooks/useMetaSEO";
import { Mail, Shield, FileText, AlertTriangle, Copyright } from "lucide-react";
import { useLanguage } from "@/hooks/useLanguage";
const Impressum = () => {
    useMetaSEO("impressum");
    const { language } = useLanguage();
    return (_jsx("div", { className: "container mx-auto py-8 px-4", children: _jsxs("div", { className: "max-w-3xl mx-auto", children: [_jsx("h1", { className: "section-title text-center mb-8", children: language === "pt" ? "Impressum / Aviso Legal" : "Impressum" }), _jsxs("div", { className: "glass-card p-8 space-y-8", children: [_jsxs("section", { children: [_jsxs("div", { className: "flex items-center gap-2 mb-4", children: [_jsx(FileText, { className: "text-seagreen" }), _jsx("h2", { className: "text-xl font-bold text-seagreen", children: language === "pt"
                                                ? "Informações conforme § 5 TMG"
                                                : "Angaben gemäß § 5 TMG" })] }), _jsx("div", { className: "pl-6 space-y-2 text-gray-700", children: _jsxs("p", { children: ["Tradicoes Portuguesas", _jsx("br", {}), "Hastedtstra\u00DFe 30", _jsx("br", {}), "21073 Hamburg", _jsx("br", {}), language === "pt" ? "Alemanha" : "Deutschland"] }) })] }), _jsxs("section", { children: [_jsxs("div", { className: "flex items-center gap-2 mb-4", children: [_jsx(Shield, { className: "text-seagreen" }), _jsx("h2", { className: "text-xl font-bold text-seagreen", children: language === "pt" ? "Representado por" : "Vertreten durch" })] }), _jsx("p", { className: "pl-6 text-gray-700", children: "Marco da Silva D\u00E1cio" })] }), _jsxs("section", { children: [_jsxs("div", { className: "flex items-center gap-2 mb-4", children: [_jsx(Mail, { className: "text-seagreen" }), _jsx("h2", { className: "text-xl font-bold text-seagreen", children: language === "pt" ? "Contato" : "Kontakt" })] }), _jsx("p", { className: "pl-6 text-gray-700", children: "E-Mail: g.c.r.f.p@hotmail.com" })] }), _jsxs("section", { children: [_jsxs("div", { className: "flex items-center gap-2 mb-4", children: [_jsx(Shield, { className: "text-seagreen" }), _jsx("h2", { className: "text-xl font-bold text-seagreen", children: language === "pt"
                                                ? "Responsável pelo conteúdo conforme § 55, parágrafo 2 RStV"
                                                : "Verantwortlich für den Inhalt nach § 55 Abs. 2 RStV" })] }), _jsx("p", { className: "pl-6 text-gray-700", children: "Marco da Silva D\u00E1cio" })] }), _jsxs("section", { children: [_jsxs("div", { className: "flex items-center gap-2 mb-4", children: [_jsx(AlertTriangle, { className: "text-seagreen" }), _jsx("h2", { className: "text-xl font-bold text-seagreen", children: language === "pt"
                                                ? "Exclusão de responsabilidade"
                                                : "Haftungsausschluss" })] }), _jsx("p", { className: "pl-6 text-gray-700", children: language === "pt"
                                        ? "Apesar do controle cuidadoso do conteúdo, não assumimos qualquer responsabilidade pelo conteúdo de links externos. Os operadores das páginas vinculadas são os únicos responsáveis pelo seu conteúdo."
                                        : "Trotz sorgfältiger inhaltlicher Kontrolle übernehmen wir keine Haftung für die Inhalte externer Links. Für den Inhalt der verlinkten Seiten sind ausschließlich deren Betreiber verantwortlich." })] }), _jsxs("section", { children: [_jsxs("div", { className: "flex items-center gap-2 mb-4", children: [_jsx(Copyright, { className: "text-seagreen" }), _jsx("h2", { className: "text-xl font-bold text-seagreen", children: language === "pt" ? "Direitos de autor" : "Urheberrecht" })] }), _jsxs("div", { className: "pl-6 space-y-4 text-gray-700", children: [_jsx("p", { children: language === "pt"
                                                ? "Todos os conteúdos utilizados neste site (textos, imagens, gráficos, logótipos) são propriedade do grupo de dança Tradicoes Portuguesas ou são utilizados com autorização. Qualquer outro uso requer consentimento prévio por escrito."
                                                : "Alle auf dieser Website verwendeten Inhalte (Texte, Bilder, Grafiken, Logos) sind Eigentum der Tanzgruppe Tradicoes Portuguesas oder werden mit freundlicher Genehmigung verwendet. Jede weitere Nutzung bedarf der vorherigen schriftlichen Zustimmung." }), _jsx("p", { children: language === "pt"
                                                ? "Se tiver conhecimento de uma possível infração de direitos autorais, pedimos que nos informe. Em caso de infrações, os conteúdos afetados serão imediatamente removidos."
                                                : "Sollten Sie auf eine mögliche Urheberrechtsverletzung aufmerksam werden, bitten wir um einen Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir entsprechende Inhalte umgehend entfernen." })] })] }), _jsxs("section", { children: [_jsxs("div", { className: "flex items-center gap-2 mb-4", children: [_jsx(AlertTriangle, { className: "text-seagreen" }), _jsx("h2", { className: "text-xl font-bold text-seagreen", children: language === "pt"
                                                ? "Objeção a publicidade"
                                                : "Werbewiderspruch" })] }), _jsx("p", { className: "pl-6 text-gray-700", children: language === "pt"
                                        ? "A utilização dos nossos dados de contacto para o envio de publicidade ou material informativo não expressamente solicitado é expressamente rejeitada. Reservamo-nos o direito de tomar medidas legais em caso de envio não solicitado de material publicitário (por exemplo, spam)."
                                        : "Der Nutzung unserer Kontaktdaten zur Übersendung von nicht ausdrücklich angeforderter Werbung oder Informationsmaterialien wird hiermit ausdrücklich widersprochen. Rechtliche Schritte im Falle von unverlangter Zusendung von Werbematerialien (z.B. Spam-Mails) bleiben vorbehalten." })] })] })] }) }));
};
export default Impressum;
