import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { useLanguage } from "@/hooks/useLanguage";
import { Dialog, DialogContent, DialogTrigger } from "@/components/ui/dialog";
const EventCard = ({ event }) => {
    const { language } = useLanguage();
    return (_jsxs("div", { className: "bg-white/90 rounded-xl shadow-md overflow-hidden flex flex-col md:flex-row card-hover h-full", children: [_jsxs(Dialog, { children: [_jsx(DialogTrigger, { asChild: true, children: _jsxs("div", { className: "md:w-1/3 relative cursor-pointer h-[250px]", children: [event.image && (_jsxs(_Fragment, { children: [event.image.endsWith(".mp4") ? (_jsx("video", { src: event.image, muted: true, loop: true, playsInline: true, className: "w-full h-full object-cover aspect-video", "aria-label": `Event Video: ${event.title} am ${event.date} in ${event.location}` })) : (_jsx("img", { src: event.image, alt: `${event.title} - ${language === "pt" ? "Evento em" : "Veranstaltung in"} ${event.location} ${language === "pt" ? "no dia" : "am"} ${new Date(event.date).toLocaleDateString(language === "pt" ? "pt-PT" : "de-DE", { day: "numeric", month: "long", year: "numeric" })}`, className: "w-full h-full object-cover aspect-video" })), event.video && (_jsx("div", { className: "absolute inset-0 flex items-center justify-center", children: _jsx("div", { className: "bg-black/50 rounded-full p-2 animate-pulse", children: _jsx("svg", { xmlns: "http://www.w3.org/2000/svg", width: "24", height: "24", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", className: "text-white", children: _jsx("polygon", { points: "5 3 19 12 5 21 5 3" }) }) }) }))] })), _jsx("div", { className: "absolute top-0 left-0 bg-seagreen text-white px-4 py-2 rounded-br-lg font-medium", children: new Date(event.date).toLocaleDateString(language === "pt" ? "pt-PT" : "de-DE", {
                                        day: "numeric",
                                        month: "short",
                                        year: "numeric",
                                    }) })] }) }), _jsx(DialogContent, { className: "p-0 max-w-2xl", children: _jsx("div", { className: "w-full", children: event.video ? (_jsxs("video", { controls: true, className: "w-full h-full max-h-[70vh]", children: [_jsx("source", { src: event.video, type: "video/mp4" }), "Your browser does not support the video tag."] })) : (event.image && (_jsx("img", { src: event.image, alt: event.title, className: "w-full h-full object-contain" }))) }) })] }), _jsxs("div", { className: "p-6 md:w-2/3 flex flex-col justify-between h-full", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-xl font-bold text-portuguesered mb-2", children: event.title }), _jsxs("div", { className: "flex items-center gap-1 text-sm text-gray-500 mb-4", children: [_jsxs("svg", { xmlns: "http://www.w3.org/2000/svg", className: "h-4 w-4", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: [_jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" }), _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M15 11a3 3 0 11-6 0 3 3 0 016 0z" })] }), _jsx("span", { children: event.location })] }), _jsx("p", { className: "text-gray-700", children: event.description })] }), event.id === 1 && (_jsx("a", { href: "https://diadeportugal.ticket.io/eg0vus7w/", target: "_blank", rel: "noopener noreferrer", className: "mt-4 button-secondary min-w-[200px] text-center self-start", children: language === "pt" ? "Comprar Bilhetes" : "Tickets kaufen" }))] })] }));
};
export default EventCard;
